version = 0.1
[default.deploy.parameters]
stack_name = "product-microservice"
resolve_s3 = true
s3_prefix = "product-microservice"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "HostedZoneId=\"Z00743383VXA4QAJRZZWR\" CertificateArn=\"arn:aws:acm:us-east-1:968225077300:certificate/c161253e-c0d5-43de-ac79-10cd4819296d\" TagEnvironment=\"production\" TagApplication=\"stock\""
image_repositories = []
