version = 0.1
[default.deploy.parameters]
stack_name = "product-stack"
resolve_s3 = true
s3_prefix = "product-stack"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TagEnvironment=\"dev\" TagProject=\"devops-na-nuvem\" LambdaAuthorizerFunctionArn=\"arn:aws:lambda:us-west-1:968225077300:function:serverless-workshop-lambda-authorizer-dev\""
image_repositories = []
