AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for Product Api

Parameters:
  TagEnvironment:
    Type: String
    Default: production
    Description: Environment Type
  TagApplication:
    Type: String
    Default: Product
    Description: Application Type

Resources:

  DynamoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: true
      PrimaryKey:
        Name: Id
        Type: String
      SSESpecification:
        SSEEnabled: true
      TableName: ProductsTable
      Tags:
        Environment: !Ref TagEnvironment
        Application: !Ref TagApplication

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: production 
      Domain:
        # DomainName: backend.devopsnanuvemweek.com
        # CertificateArn: !Ref CertificateArn
        # Route53:
        #   HostedZoneId: !Ref HostedZoneId
        # Não precisa de base path
        BasePath:
        - products
      Tags:
        Environment: !Ref TagEnvironment
        Application: !Ref TagApplication

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ProductApi
      Runtime: nodejs22.x
      Handler: handler.main
      Timeout: 30
      Environment:
        Variables:
          DYNAMO_TABLE_NAME: !Ref DynamoTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        Products:
          Type: Api
          Properties:
            Path: /Products
            Method: ANY
            RestApiId: !Ref ApiGateway
        ProductsById:
          Type: Api
          Properties:
            Path: /Products/{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway
      Tags:
        Environment: !Ref TagEnvironment
        Application: !Ref TagApplication

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/production/Products"
  ApiFunction:
    Description: "API Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn
  DynamoTable:
    Description: "DynamoDB Table ARN"
    Value: !GetAtt DynamoTable.Arn