AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for Product Api

Parameters:
  TagEnvironment:
    Type: String
    Default: production
    Description: Environment Type
  TagApplication:
    Type: String
    Default: product
    Description: Application Type
  LambdaAuthorizerFunctionArn:
    Type: String
    Description: Lambda Authorizer Function ARN

Resources:

  DynamoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: true
      PrimaryKey:
        Name: Id
        Type: String
      SSESpecification:
        SSEEnabled: true
      TableName: ProductsTable
      Tags:
        Environment: !Ref TagEnvironment
        Application: !Ref TagApplication

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: production 
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionArn: !Ref LambdaAuthorizerFunctionArn
            IdentitySource: method.request.header.Authorization
            Type: REQUEST
      Tags:
        Environment: !Ref TagEnvironment
        Application: !Ref TagApplication

  ApiGatewayBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: products
      DomainName: backend.devopsnanuvemweek.com
      RestApiId: !Ref ApiGateway
      Stage: !Ref ApiGateway.Stage

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ProductApi
      Runtime: nodejs22.x
      Handler: handler.main
      Timeout: 30
      Environment:
        Variables:
          DYNAMO_TABLE_NAME: !Ref DynamoTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        Products:
          Type: Api
          Properties:
            Path: /products
            Method: ANY
            RestApiId: !Ref ApiGateway
        ProductsById:
          Type: Api
          Properties:
            Path: /products/{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway
      Tags:
        Environment: !Ref TagEnvironment
        Application: !Ref TagApplication

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/production/products"
  ApiFunction:
    Description: "API Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn
  DynamoTable:
    Description: "DynamoDB Table ARN"
    Value: !GetAtt DynamoTable.Arn