version = 0.1
[default.deploy.parameters]
stack_name = "stock-app"
resolve_s3 = true
s3_prefix = "stock-app"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TagEnvironment=\"production\" TagProject=\"devops-na-nuvem\" LambdaAuthorizerArn=\"arn:aws:lambda:us-west-1:968225077300:function:serverless-workshop-lambda-authorizer-production\""
image_repositories = []
