AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  TagEnvironment:
    Type: String
    Default: production
  TagProject:
    Type: String
    Default: devops-na-nuvem
  LambdaAuthorizerArn:
    Type: String

Resources:

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub serverless-workshop-table-stock-${TagEnvironment}
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      PrimaryKey:
        Name: Id
        Type: String
      Tags:
        Environment: !Ref TagEnvironment
        Project: !Ref TagProject

  ApiGatewayPathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: stocks
      DomainName: backend.devopsnanuvemweek.com
      RestApiId: !Ref ApiGatewayApi
      Stage: !Ref ApiGatewayApi.Stage
      
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub serverless-workshop-api-stock-${TagEnvironment}
      StageName: prod
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionArn: !Ref LambdaAuthorizerArn
            Identity:
              Header: Authorization
            Type: TOKEN
      Tags:
        Environment: !Ref TagEnvironment
        Project: !Ref TagProject

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub serverless-workshop-api-stock-${TagEnvironment}
      Runtime: dotnet8
      Handler: StockApi
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMO_TABLE_NAME: !Ref DynamoDBTable
      Events:
        StockRootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi
        StockAnythingElsePath:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi
      Tags:
        Environment: !Ref TagEnvironment
        Project: !Ref TagProject