AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  TagEnvironment:
    Type: String
  TagProject:
    Type: String
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String

Resources:

  LambdaAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub serverless-workshop-lambda-authorizer-${TagEnvironment}
      Runtime: python3.12
      Timeout: 30
      Handler: authorizer.lambda_handler
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref CognitoUserPool
          COGNITO_REGION: !Ref AWS::Region
      Tags:
        Environment: !Ref TagEnvironment
        Project: !Ref TagProject

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub serverless-workshop-cognito-user-pool-${TagEnvironment}
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub serverless-workshop-cognito-user-pool-client-${TagEnvironment}
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  CustomDomainAlias:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref CertificateArn
      DomainName: !Sub backend-${TagEnvironment}.devopsnanuvem.com
      EndpointConfiguration: 
        Types: 
        - EDGE
      SecurityPolicy: TLS_1_2
  
  CustomDomainRecordRoute53:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget: 
        DNSName: !GetAtt CustomDomainAlias.DistributionDomainName
        HostedZoneId: !GetAtt CustomDomainAlias.DistributionHostedZoneId
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub backend-${TagEnvironment}.devopsnanuvem.com
      Type: A
